services:
  mysql:
    image: mysql:8.0
    container_name: game-expert-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: game_expert
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: game-expert-redis
    ports:
      - "6379:6379"